"""empty message

Revision ID: 97ee2916af0a
Revises: 
Create Date: 2023-01-17 20:56:30.539807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ee2916af0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('media_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('answer', sa.VARCHAR(length=64), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
